export const environment = {
  production: false,
  // Empty string → requests go to the dev-server origin, which proxies to the
  // backend via proxy.conf.json (regenerated by scripts/find-ports.js).
  apiUrl: '',
}
