from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    # Load .env first, then .env.ports (generated by scripts/find-ports.js) so
    # the discovered ports override defaults without touching the main .env file.
    model_config = SettingsConfigDict(env_file=(".env", ".env.ports"), extra="ignore")

    # App
    app_name: str = "DocuMind"
    app_env: str = "development"
    secret_key: str
    access_token_expire_minutes: int = 60
    refresh_token_expire_days: int = 30

    # MongoDB
    mongodb_url: str = "mongodb://localhost:27017"
    mongodb_db_name: str = "documind"

    # Redis
    redis_url: str = "redis://localhost:6379/0"

    # Celery
    celery_broker_url: str = "redis://localhost:6379/1"
    celery_result_backend: str = "redis://localhost:6379/2"

    # Storage
    storage_provider: str = "minio"  # minio | s3
    s3_endpoint_url: str = "http://localhost:9000"
    s3_access_key: str = "minioadmin"
    s3_secret_key: str = "minioadmin"
    s3_bucket_name: str = "documind"

    # LLM
    llm_provider: str = "openai"  # openai | anthropic
    llm_model: str = "gpt-4o-mini"
    embedding_model: str = "text-embedding-3-small"
    openai_api_key: str = ""
    anthropic_api_key: str = ""

    # Ports (written by scripts/find-ports.js into .env.ports)
    frontend_port: int = 5173
    admin_port: int = 4200
    backend_port: int = 8000

    # CORS — extra origins to allow beyond the auto-derived localhost ones
    allowed_origins: list[str] = []

    # Limits
    max_upload_size_bytes: int = 50 * 1024 * 1024  # 50 MB
    allowed_mime_types: list[str] = [
        "application/pdf",
        "text/csv",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "text/plain",
    ]


settings = Settings()
